### ISSUE TITLE
add VBN GTFS datasets

### ISSUE THREAD

**Issue by derhuerst** [mfdz/gtfs-hub#41]
I found a [Pastbin note](https://pastebin.com/kTsU96KG) on the internet that links to VBN download links ([Web Archive version](https://web.archive.org/web/20230505121818/)).

Inspecting the `https://connect-info.net` page, it seems like the feeds are [those mentioned on the VBN "open data" page](https://www.vbn.de/service/entwicklerinfos/opendata-und-openservice).

**Comment by hbruch** [comment]
All these datasets are already included as [NDS, NDS-toplevel, NDS-toplevel-dhid](https://github.com/mfdz/gtfs-hub/blob/master/config/gtfs-feeds.csv#L18-L20) and [NAH-SH](https://github.com/mfdz/gtfs-hub/blob/master/config/gtfs-feeds.csv#L16). As the token is private, I provide it as ENV param. 

Do you suggest to replace it by the one published via pastebin? I'd rather prefer not to do this.

**Comment by derhuerst** [comment]
No, I guess having the env-based ones should be sufficient.
